/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import communication.Operation;
import domain.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import thread.CheckThread;
import ui.controller.Controller;

/**
 *
 * @author HP
 */
public class FrmMain extends javax.swing.JFrame {

    private User user;

    /**
     * Creates new form FrmMain
     */
    public FrmMain(User user) {
        this.user = user;
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        setTitle("Komunalno preduzece, korisnik: " + user.getUsername());
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        CheckThread ct = new CheckThread();
        ct.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnOdjava = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBarMain = new javax.swing.JMenuBar();
        menuKR = new javax.swing.JMenu();
        newKRItem = new javax.swing.JMenuItem();
        viewEditKRItem = new javax.swing.JMenuItem();
        menuKamion = new javax.swing.JMenu();
        newKamionItem = new javax.swing.JMenuItem();
        viewEditKamionItem = new javax.swing.JMenuItem();
        menuMesto = new javax.swing.JMenu();
        newMestoItem = new javax.swing.JMenuItem();
        viewEditMesto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOdjava.setText("Odjava");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Seminarski\\Pozadina.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 275, 74, 283);
        jPanel1.add(jLabel1, gridBagConstraints);

        menuKR.setText("Komunalni radnik (KR)");

        newKRItem.setText("Dodaj KR");
        newKRItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newKRItemActionPerformed(evt);
            }
        });
        menuKR.add(newKRItem);

        viewEditKRItem.setText("Prikazi ili izmeni KR");
        viewEditKRItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditKRItemActionPerformed(evt);
            }
        });
        menuKR.add(viewEditKRItem);

        menuBarMain.add(menuKR);

        menuKamion.setText("Kamion");

        newKamionItem.setText("Dodaj kamion");
        newKamionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newKamionItemActionPerformed(evt);
            }
        });
        menuKamion.add(newKamionItem);

        viewEditKamionItem.setText("Prikazi ili izmeni kamion");
        viewEditKamionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditKamionItemActionPerformed(evt);
            }
        });
        menuKamion.add(viewEditKamionItem);

        menuBarMain.add(menuKamion);

        menuMesto.setText("Mesto");

        newMestoItem.setText("Dodaj mesto");
        newMestoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMestoItemActionPerformed(evt);
            }
        });
        menuMesto.add(newMestoItem);

        viewEditMesto.setText("Prikazi ili izmeni mesto");
        viewEditMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEditMestoActionPerformed(evt);
            }
        });
        menuMesto.add(viewEditMesto);

        menuBarMain.add(menuMesto);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOdjava)
                .addGap(25, 25, 25))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnOdjava)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newKRItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newKRItemActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            JDialog dialog = new FrmNewEditKR(this, true, Operation.ADD_KR);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            //ne zelimo skroz da izadjemo, samo da zatvorimo dijalog
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newKRItemActionPerformed

    private void viewEditKRItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEditKRItemActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            JDialog dialog = new FrmViewAllKR(this, true);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            //ne zelimo skroz da izadjemo, samo da zatvorimo dijalog
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewEditKRItemActionPerformed

    private void newKamionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newKamionItemActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            JDialog dialog = new FrmNewEditKa(this, true, Operation.ADD_KA);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            //ne zelimo skroz da izadjemo, samo da zatvorimo dijalog
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newKamionItemActionPerformed

    private void viewEditKamionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEditKamionItemActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            JDialog dialog = new FrmViewAllKa(this, true);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            //ne zelimo skroz da izadjemo, samo da zatvorimo dijalog
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewEditKamionItemActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        // TODO add your handling code here:
        try {
            Controller.getInstance().logout(user);

            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri odjavljivanju!\n" + ex.getMessage(), "Logout", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void newMestoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMestoItemActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            JDialog dialog = new FrmNewEditMesto(this,true, Operation.ADD_M);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            //ne zelimo skroz da izadjemo, samo da zatvorimo dijalog
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newMestoItemActionPerformed

    private void viewEditMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEditMestoActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:

            JDialog dialog = new FrmViewAllMesta(this, true);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            //ne zelimo skroz da izadjemo, samo da zatvorimo dijalog
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setVisible(true);

        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewEditMestoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuKR;
    private javax.swing.JMenu menuKamion;
    private javax.swing.JMenu menuMesto;
    private javax.swing.JMenuItem newKRItem;
    private javax.swing.JMenuItem newKamionItem;
    private javax.swing.JMenuItem newMestoItem;
    private javax.swing.JMenuItem viewEditKRItem;
    private javax.swing.JMenuItem viewEditKamionItem;
    private javax.swing.JMenuItem viewEditMesto;
    // End of variables declaration//GEN-END:variables
}
