/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.form;

import communication.Operation;
import domain.Kamion;
import domain.Vozac;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import ui.controller.Controller;

/**
 *
 * @author HP
 */
public class FrmNewEditKa extends javax.swing.JDialog {

    private Operation mode;
    private Kamion kamion;

    /**
     * Creates new form FrmNewEditK
     */
    public FrmNewEditKa(java.awt.Frame parent, boolean modal, Operation mode) throws Exception {
        super(parent, modal);
        this.mode = mode;
        initComponents();
        setLocationRelativeTo(null);
        fillVozaci();
        setTitle("Cuvanje kamiona");
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModel = new javax.swing.JLabel();
        btnObrisi = new javax.swing.JButton();
        lblNosivost = new javax.swing.JLabel();
        btnIzmena = new javax.swing.JButton();
        lblVozac = new javax.swing.JLabel();
        txtBrend = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtNosivost = new javax.swing.JTextField();
        lblBrend = new javax.swing.JLabel();
        comboBoxVozac = new javax.swing.JComboBox<>();
        btnSacuvaj = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModel.setText("Model:");

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lblNosivost.setText("Nosivost:");

        btnIzmena.setText("Omoguci izmenu");
        btnIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaActionPerformed(evt);
            }
        });

        lblVozac.setText("Vozac:");

        lblBrend.setText("Brend:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        lblID.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnObrisi)
                .addGap(80, 80, 80)
                .addComponent(btnIzmena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(lblVozac)
                            .addGap(63, 63, 63))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNosivost)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBrend)
                                    .addComponent(lblModel)))
                            .addGap(54, 54, 54)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblID)
                        .addGap(80, 80, 80)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBrend)
                            .addComponent(txtNosivost, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                            .addComponent(comboBoxVozac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNosivost)
                            .addComponent(txtNosivost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrend))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModel))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVozac)
                    .addComponent(comboBoxVozac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmena))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
            Kamion ka = new Kamion();
            String idText = txtID.getText();
            if (!idText.isEmpty()) {
                ka.setKamionID(Long.parseLong(idText));
            } else {
                ka.setKamionID(null);
            }
            ka.setBrend(txtBrend.getText());
            ka.setModel(txtModel.getText());
            ka.setNosivost(Long.parseLong(txtNosivost.getText()));
            if (ka.getNosivost() <= 0) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti kamion!");

            } else {
                ka.setVozac((Vozac) comboBoxVozac.getSelectedItem());
                System.out.println("Na strani forme su " + ka);
                if (mode == Operation.ADD_KA) {
                    Controller.getInstance().createKa(ka);
                } else {
                    Controller.getInstance().editKa(ka);
                }
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio kamion!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti kamion!");

        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaActionPerformed
        // TODO add your handling code here:
        mode = Operation.EDIT_KA;
        prepareForm();
    }//GEN-LAST:event_btnIzmenaActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        // TODO add your handling code here:
        //prvo ucitamo pa brisemo
        try {
            Kamion ka = new Kamion();
            String idText = txtID.getText();
            if (!idText.isEmpty()) {
                ka.setKamionID(Long.parseLong(idText));
            } else {
                ka.setKamionID(null);
            }
            ka.setBrend(txtBrend.getText());
            ka.setModel(txtModel.getText());
            ka.setNosivost(Long.parseLong(txtNosivost.getText()));
            ka.setVozac((Vozac) comboBoxVozac.getSelectedItem());

            Kamion ucitani = Controller.getInstance().getKa(ka);
            System.out.println("Ucitani je " + ucitani);

            if (ucitani != null) {
                JOptionPane.showMessageDialog(this, "Sistem je ucitao kamion!");
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita kamion!");
            }

            int odg = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete kamion?", "Provera", JOptionPane.YES_NO_OPTION);
            if (odg == JOptionPane.YES_OPTION) {
                Kamion obrisani = Controller.getInstance().deleteKa(ka);
                JOptionPane.showMessageDialog(this, "Sistem je obrisao kamion!");

                System.out.println("Obrisani je " + obrisani);

                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise kamion!");

                dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise kamion!");

        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    public FrmNewEditKa(java.awt.Frame parent, boolean modal, Operation mode, Kamion ka) throws Exception {
        super(parent, modal);

        initComponents();
        setLocationRelativeTo(null);
        this.mode = mode;

        kamion = ka;
        fillVozaci();
        setTitle("Cuvanje kamiona");

        prepareForm();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmena;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> comboBoxVozac;
    private javax.swing.JLabel lblBrend;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblNosivost;
    private javax.swing.JLabel lblVozac;
    private javax.swing.JTextField txtBrend;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNosivost;
    // End of variables declaration//GEN-END:variables

    private void fillVozaci() throws Exception {
        try {
            List<Vozac> vozaci = Controller.getInstance().getAllVozaci();
            comboBoxVozac.setModel(new DefaultComboBoxModel(vozaci.toArray()));

            comboBoxVozac.setSelectedIndex(-1);

        } catch (Exception ex) {
            //ako slucajno dodje do greske
            ex.printStackTrace();
        }
    }

    private void prepareForm() {

        comboBoxVozac.setEditable(false);
        switch (mode) {
            case ADD_KA: {
                btnObrisi.setEnabled(false);
                btnIzmena.setVisible(false);
                btnSacuvaj.setVisible(true);
                comboBoxVozac.setEnabled(true);
                lblID.setVisible(false);
                txtID.setVisible(false);
                break;

            }
            case EDIT_KA: {
                txtBrend.setEnabled(true);
                txtModel.setEnabled(true);
                txtNosivost.setEnabled(true);

                txtID.setEnabled(true);
                txtID.setEditable(false);

                btnObrisi.setEnabled(true);
                btnIzmena.setEnabled(false);
                btnSacuvaj.setEnabled(true);
                comboBoxVozac.setEnabled(true);
                break;
            }
            case VIEW_KA: {
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, "Sistem je ucitao kamion!");
                });
                btnObrisi.setEnabled(true);
                btnIzmena.setEnabled(true);
                btnSacuvaj.setEnabled(false);
                txtID.setEnabled(false);
                txtID.setEditable(false);
                txtID.setText(kamion.getKamionID().toString());
                txtBrend.setText(kamion.getBrend());
                txtModel.setText(kamion.getModel());
                txtNosivost.setText(kamion.getNosivost().toString());

                comboBoxVozac.setSelectedItem(kamion.getVozac());

                txtBrend.setEnabled(false);
                txtModel.setEnabled(false);
                txtNosivost.setEnabled(false);
                comboBoxVozac.setEnabled(false);

                break;

            }

        }
    }
}
